# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  - master

variables:
  system.debug: true

jobs:
  - job: Linux
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - checkout: self
        submodules: recursive
      - task: Cache@2
        displayName: Cache vcpkg
        inputs:
          key: $(Build.SourcesDirectory)/vcpkg-ports.txt | $(Build.SourcesDirectory)/.git/modules/vcpkg/HEAD | "$(Agent.OS)"
          path: "$(Build.SourcesDirectory)/vcpkg"
      - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
        inputs:
          vcpkgArguments: "@$(Build.SourcesDirectory)/vcpkg-ports.txt --triplet x64-linux"
          vcpkgDirectory: "$(Build.SourcesDirectory)/vcpkg"
      - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
        inputs:
          useVcpkgToolchainFile: true
  - job: macOS
    pool:
      vmImage: "macOS-latest"
    steps:
      - checkout: self
        submodules: recursive
      - task: Cache@2
        displayName: Cache vcpkg
        inputs:
          key: $(Build.SourcesDirectory)/vcpkg-ports.txt | $(Build.SourcesDirectory)/.git/modules/vcpkg/HEAD | "$(Agent.OS)"
          path: "$(Build.SourcesDirectory)/vcpkg"
      - script: |
          brew install gcc
          sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target / -allowUntrusted
      - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
        inputs:
          vcpkgArguments: "@$(Build.SourcesDirectory)/vcpkg-ports.txt --triplet x64-osx"
          vcpkgDirectory: "$(Build.SourcesDirectory)/vcpkg"
      - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
        inputs:
          useVcpkgToolchainFile: true
  - job: Windows
    pool:
      vmImage: "windows-latest"
    steps:
      - checkout: self
        submodules: recursive
      - task: Cache@2
        displayName: Cache vcpkg
        inputs:
          key: $(Build.SourcesDirectory)/vcpkg-ports.txt | $(Build.SourcesDirectory)/.git/modules/vcpkg/HEAD | "$(Agent.OS)"
          path: "$(Build.SourcesDirectory)/vcpkg"
      - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
        inputs:
          vcpkgArguments: "@$(Build.SourcesDirectory)/vcpkg-ports.txt --triplet x64-windows"
          vcpkgDirectory: "$(Build.SourcesDirectory)/vcpkg"
      - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
        inputs:
          useVcpkgToolchainFile: true
